eureka:
    dashboard:
        enabled: true
        path: /${spring.application.name}/dashboard
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        region: us-east-1
    instance:
        hostname: localhost
        prefer-ip-address: true
management:
    endpoint:
        health:
            enabled: true
    endpoints:
        web:
            base-path: /discovery
            exposure:
                include:
                    - 'health'
server:
    port: 8761
    servlet:
        context-path: /
spring:
    application:
        name: discovery
