logging:
    charset:
        console: UTF-8
    level:
        ninja.digitalcloud.cloud.filemanager.*: DEBUG
management:
    endpoint:
        health:
            enabled: true
        info:
            enabled: true
    endpoints:
        web:
            base-path: /filemanager
            exposure:
                include:
                    - 'info'
                    - 'health'
server:
    compression:
        enabled: true
    error:
        include-exception: false
        include-message: always
        path: /error
        whitelabel:
            enabled: false
    forward-headers-strategy: framework
    port: 8082
    servlet:
        context-path: /v1/api
spring:
    application:
        name: filemanager
    datasource:
        password: ${DATABASE_PASSWORD:ChangeMeNow!}
        url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
        username: ${DATABASE_USERNAME:postgres}
    docker:
        compose:
            enabled: true
            profiles:
                active: default
    flyway:
        create-schemas: true
        default-schema: filemanager
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        open-in-view: true
    servlet:
        multipart:
            file-size-threshold: 2KB
            max-file-size: 1MB
            max-request-size: 1MB
springdoc:
    api-docs:
        enabled: true
        path: /filemanager/api-docs
        version: OPENAPI_3_1
    enable-data-rest: false
    enable-hateoas: false
    swagger-ui:
        enabled: false
